name: Actions Workflow 

on:
  push:
    branches:
      - master
    paths: 
      - "**.html"
    
jobs: 
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
